#include "common.hpp"
#include "httplib/jwt.hpp"
#include "httplib/server/middleware/data.hpp"
#include "httplib/server/middleware/jwt_auth.hpp"
#include "httplib/server/request.hpp"
#include "httplib/server/response.hpp"

#include <catch2/catch_test_macros.hpp>
#include <jwt-cpp/jwt.h>
#include <jwt-cpp/traits/boost-json/traits.h>

using namespace std::chrono_literals;
using traits = jwt::traits::boost_json;
using claim = jwt::basic_claim<traits>;

namespace
{
    using test_common::run;
    using test_common::setup_logger;

} // namespace

TEST_CASE("JWT: build and sign with HS256", "[jwt]")
{
    auto token
        = httplib::jwt::create().set_type("access").set_issued_now().set_expires_in(1h).set_subject("user123").sign(
            httplib::jwt::hs256("my-secret"));

    REQUIRE(!token.empty());
    REQUIRE(std::count(token.begin(), token.end(), '.') == 2);
}

TEST_CASE("JWT: minimal token", "[jwt]")
{
    auto token = httplib::jwt::create().sign(httplib::jwt::hs256("x"));
    REQUIRE(!token.empty());
}

TEST_CASE("JWT: decode token", "[jwt]")
{
    auto token = httplib::jwt::create().set_subject("user123").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    REQUIRE(decoded.get_payload_claim<std::string>("sub") == "user123");
}

TEST_CASE("JWT: verify token", "[jwt]")
{
    auto token = httplib::jwt::create().set_payload_claim("id", 42).sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    REQUIRE(decoded.verify(httplib::jwt::hs256("secret")));

    boost::system::error_code ec;
    REQUIRE_FALSE(decoded.verify(httplib::jwt::hs256("wrong"), ec));
    REQUIRE(ec == make_error_code(httplib::jwt::error::signature_verification));
}

TEST_CASE("JWT: verifier with claims", "[jwt]")
{
    auto token = httplib::jwt::create().set_issuer("my-app").set_subject("alice").set_id("jti-1").set_issued_now().sign(
        httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs256("secret"))
        .with_issuer("my-app")
        .with_subject("alice")
        .with_id("jti-1")
        .verify(decoded, ec);
    REQUIRE_FALSE(ec);

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_issuer("wrong").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::issuer_mismatch));
}

TEST_CASE("JWT: cross-validate with jwt-cpp", "[jwt]")
{
    auto token = httplib::jwt::create()
                     .set_issuer("httplib")
                     .set_subject("test")
                     .set_id("abc123")
                     .set_issued_now()
                     .set_expires_in(1h)
                     .sign(httplib::jwt::hs256("shared-secret"));

    // jwt-cpp can decode and verify our token
    auto decoded = ::jwt::decode<traits>(token);
    REQUIRE(decoded.has_issuer());
    REQUIRE(decoded.get_issuer() == "httplib");
    REQUIRE(decoded.has_subject());
    REQUIRE(decoded.get_subject() == "test");
    REQUIRE(decoded.get_algorithm() == "HS256");

    auto verifier
        = ::jwt::verify<traits>().allow_algorithm(::jwt::algorithm::hs256 { "shared-secret" }).with_issuer("httplib");
    verifier.verify(decoded);

    // Also verify our decoded token matches jwt-cpp's
    auto our_decoded = httplib::jwt::decode(token).value();
    REQUIRE(our_decoded.get_algorithm() == "HS256");
    REQUIRE(our_decoded.has_issuer());
    REQUIRE(our_decoded.get_issuer() == "httplib");
    REQUIRE(our_decoded.has_subject());
    REQUIRE(our_decoded.get_subject() == "test");
    REQUIRE(our_decoded.has_id());
    REQUIRE(our_decoded.get_id() == "abc123");
}

TEST_CASE("JWT: verify tokens generated by jwt-cpp", "[jwt]")
{
    // jwt-cpp generates a token, our library decodes and verifies it
    auto jwt_cpp_token
        = ::jwt::create<traits>().set_issuer("jwt-cpp").set_subject("cross").set_id("x123").set_issued_now().sign(
            ::jwt::algorithm::hs256 { "shared-secret" });

    auto decoded = httplib::jwt::decode(jwt_cpp_token).value();
    REQUIRE(decoded.get_algorithm() == "HS256");
    REQUIRE(decoded.has_issuer());
    REQUIRE(decoded.get_issuer() == "jwt-cpp");
    REQUIRE(decoded.has_subject());
    REQUIRE(decoded.get_subject() == "cross");
    REQUIRE(decoded.has_id());
    REQUIRE(decoded.get_id() == "x123");

    httplib::jwt::verify(httplib::jwt::hs256("shared-secret"))
        .with_issuer("jwt-cpp")
        .with_subject("cross")
        .with_id("x123")
        .verify(decoded);
}

TEST_CASE("JWT: different secrets produce different tokens", "[jwt]")
{
    auto t1 = httplib::jwt::create().set_issued_now().sign(httplib::jwt::hs256("s1"));
    auto t2 = httplib::jwt::create().set_issued_now().sign(httplib::jwt::hs256("s2"));
    REQUIRE(t1 != t2);
}

TEST_CASE("JWT: HS384 and HS512", "[jwt]")
{
    auto t384 = httplib::jwt::create().set_subject("test").sign(httplib::jwt::hs384("secret"));

    auto decoded384 = httplib::jwt::decode(t384).value();
    REQUIRE(decoded384.get_algorithm() == "HS384");
    REQUIRE(decoded384.verify(httplib::jwt::hs384("secret")));

    auto t512 = httplib::jwt::create().set_subject("test").sign(httplib::jwt::hs512("secret"));

    auto decoded512 = httplib::jwt::decode(t512).value();
    REQUIRE(decoded512.get_algorithm() == "HS512");
    REQUIRE(decoded512.verify(httplib::jwt::hs512("secret")));
}

TEST_CASE("JWT: header claims and time claims", "[jwt]")
{
    auto now = std::chrono::system_clock::now();
    auto token = httplib::jwt::create()
                     .set_type("JWT")
                     .set_content_type("JWT")
                     .set_key_id("key-1")
                     .set_header_claim("custom-hdr", "hdr-val")
                     .set_audience("api.example.com")
                     .set_not_before(now - 1h)
                     .set_expires_at(now + 1h)
                     .set_issued_at(now)
                     .set_payload_claim("role", "admin")
                     .sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    REQUIRE(decoded.get_algorithm() == "HS256");
    REQUIRE(decoded.has_audience());
    REQUIRE(decoded.get_audience() == "api.example.com");
    REQUIRE(decoded.has_not_before());
    REQUIRE(decoded.has_expires_at());
    REQUIRE(decoded.has_issued_at());
}

TEST_CASE("JWT: verifier with_audience and with_claim", "[jwt]")
{
    auto token = httplib::jwt::create()
                     .set_audience("api.example.com")
                     .set_payload_claim("role", "admin")
                     .sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_audience("api.example.com").verify(decoded, ec);
    REQUIRE_FALSE(ec);

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_audience("wrong").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::audience_mismatch));

    httplib::jwt::verify(httplib::jwt::hs256("secret"))
        .with_claim("role", [](boost::json::value const& v) { return v == "admin"; })
        .verify(decoded, ec);
    REQUIRE_FALSE(ec);
}

TEST_CASE("JWT: error_code for each mismatch type", "[jwt]")
{
    auto token = httplib::jwt::create().set_subject("alice").set_id("jti-x").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    boost::system::error_code ec;

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_subject("bob").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::subject_mismatch));

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_id("wrong-id").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::id_mismatch));
}

TEST_CASE("JWT: decoded_jwt accessors", "[jwt]")
{
    auto token = httplib::jwt::create().set_issuer("test-iss").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    REQUIRE(!decoded.get_token().empty());
    REQUIRE(!decoded.get_signature().empty());
    REQUIRE(decoded.get_header().is_object());
    REQUIRE(decoded.get_payload().is_object());
}

// 回归：decoded_jwt 的公开构造函数过去会抛未文档化的异常（json::parse / value::at /
// value_to 都是抛异常的 overload），头文件对此只字未提。现在除 bad_alloc 外一律不抛，
// 失败原因记在 get_error()。
//
// decode() 过去用 catch (std::exception) 兜住，于是连 std::bad_alloc 也会被报成
// invalid_token —— 分配失败被当成"token 非法"。现在 decode() 读 error_，不再吞异常。
TEST_CASE("JWT: decoded_jwt constructor does not throw on malformed token", "[jwt]")
{
    // base64url 字面量：not json at all / {"alg":"HS256"} / {} / {"alg":123} / [1,2,3] / {{{
    // （jwt.cpp 里的 base64url_encode 是内部符号，测试用不了，只能写字面量。）
    const char* b64_bad_json = "bm90IGpzb24gYXQgYWxs";
    const char* b64_alg_str = "eyJhbGciOiJIUzI1NiJ9";
    const char* b64_empty_obj = "e30";
    const char* b64_alg_num = "eyJhbGciOjEyM30";
    const char* b64_json_array = "WzEsMiwzXQ";
    const char* b64_bad_payload = "e3t7";

    auto token = [](std::string_view h, std::string_view p)
    { return std::string(h) + "." + std::string(p) + ".sig"; };

    SECTION("header is not valid JSON")
    {
        auto t = token(b64_bad_json, b64_empty_obj);
        REQUIRE_NOTHROW([&] { httplib::jwt::decoded_jwt d(t); });
        httplib::jwt::decoded_jwt d(t);
        REQUIRE(d.get_error() == make_error_code(httplib::jwt::error::invalid_token));
    }

    SECTION("payload is not valid JSON")
    {
        httplib::jwt::decoded_jwt d(token(b64_alg_str, b64_bad_payload));
        REQUIRE(d.get_error() == make_error_code(httplib::jwt::error::invalid_token));
    }

    SECTION("alg claim missing")
    {
        httplib::jwt::decoded_jwt d(token(b64_empty_obj, b64_empty_obj));
        REQUIRE(d.get_error() == make_error_code(httplib::jwt::error::invalid_token));
    }

    SECTION("alg claim is not a string")
    {
        httplib::jwt::decoded_jwt d(token(b64_alg_num, b64_empty_obj));
        REQUIRE(d.get_error() == make_error_code(httplib::jwt::error::invalid_token));
    }

    SECTION("header is a JSON array, not an object")
    {
        httplib::jwt::decoded_jwt d(token(b64_json_array, b64_empty_obj));
        REQUIRE(d.get_error() == make_error_code(httplib::jwt::error::invalid_token));
    }

    SECTION("no dots at all")
    {
        httplib::jwt::decoded_jwt d("garbage");
        REQUIRE(d.get_error() == make_error_code(httplib::jwt::error::invalid_token));
    }

    SECTION("valid token reports no error")
    {
        auto t = httplib::jwt::create().set_issuer("iss").sign(httplib::jwt::hs256("secret"));
        httplib::jwt::decoded_jwt d(t);
        REQUIRE_FALSE(d.get_error());
        REQUIRE(d.get_algorithm() == "HS256");
    }
}

// decode() 的对外契约没变：以上每种坏 token 仍然报 invalid_token。
TEST_CASE("JWT: decode still reports invalid_token for malformed tokens", "[jwt]")
{
    auto bad = {
        std::string("no-dots"),
        std::string("only.one"),
        std::string("bm90IGpzb24gYXQgYWxs.e30.sig"),        // header 非 JSON
        std::string("eyJhbGciOiJIUzI1NiJ9.e3t7.sig"),       // payload 非 JSON
        std::string("e30.e30.sig"),                          // 缺 alg
        std::string("eyJhbGciOjEyM30.e30.sig"),              // alg 非字符串
        std::string("WzEsMiwzXQ.e30.sig"),                   // header 是数组
    };

    for (auto const& t : bad)
    {
        auto res = httplib::jwt::decode(t);
        REQUIRE_FALSE(res.has_value());
        REQUIRE(res.error() == make_error_code(httplib::jwt::error::invalid_token));
    }

    auto good = httplib::jwt::create().sign(httplib::jwt::hs256("secret"));
    auto res = httplib::jwt::decode(good);
    REQUIRE(res.has_value());
    REQUIRE(res.value().get_algorithm() == "HS256");
}

TEST_CASE("JWT: verifier allow_algorithm explicitly", "[jwt]")
{
    auto token = httplib::jwt::create().sign(httplib::jwt::hs256("secret"));
    auto decoded = httplib::jwt::decode(token).value();

    httplib::jwt::verifier v;
    v.allow_algorithm(httplib::jwt::hs256("secret"));
    boost::system::error_code ec;
    v.verify(decoded, ec);
    REQUIRE_FALSE(ec);
}

TEST_CASE("JWT: middleware auth via Bearer token", "[jwt]")
{
    namespace mw = httplib::server::middleware;

    auto ja = mw::jwt_auth_middleware { httplib::jwt::hs256("secret") };
    ja.with_issuer("my-app");

    auto token = httplib::jwt::create().set_issuer("my-app").set_subject("alice").sign(httplib::jwt::hs256("secret"));

    run(
        [&](auto& server)
        {
            server.router().template set_http_handler<httplib::method::get>(
                "/protected",
                [](httplib::server::request& req, httplib::server::response& resp)
                {
                    auto jwt = mw::fetch<mw::jwt_auth_middleware>(req);
                    resp.set_string_content(jwt.get_subject(), "text/plain");
                },
                ja);
        },
        [&](auto& client) -> net::awaitable<void>
        {
            auto hdrs = httplib::headers();
            hdrs.set(httplib::field::authorization, "Bearer " + token);
            httplib::client::request req(httplib::method::get, "/protected", hdrs);
            auto resp = UNWRAP(co_await client.async_send_request(req));
            REQUIRE(resp.result() == httplib::status::ok);
            REQUIRE(test_common::as_string(resp) == "alice");
            co_return;
        });
}

TEST_CASE("JWT: middleware rejects invalid token", "[jwt]")
{
    namespace mw = httplib::server::middleware;

    run(
        [](auto& server)
        {
            server.router().template set_http_handler<httplib::method::get>(
                "/protected",
                [](httplib::server::request&, httplib::server::response& resp)
                { resp.set_string_content("ok"sv, "text/plain"sv); },
                mw::jwt_auth_middleware { httplib::jwt::hs256("secret") });
        },
        [](auto& client) -> net::awaitable<void>
        {
            auto hdrs = httplib::headers();
            hdrs.set(httplib::field::authorization, "Bearer invalid.token.here");
            httplib::client::request req(httplib::method::get, "/protected", hdrs);
            auto resp = UNWRAP(co_await client.async_send_request(req));
            REQUIRE(resp.result() == httplib::status::unauthorized);
            co_return;
        });
}

TEST_CASE("JWT: middleware rejects missing Bearer", "[jwt]")
{
    namespace mw = httplib::server::middleware;

    run(
        [](auto& server)
        {
            server.router().template set_http_handler<httplib::method::get>(
                "/protected",
                [](httplib::server::request&, httplib::server::response& resp)
                { resp.set_string_content("ok"sv, "text/plain"sv); },
                mw::jwt_auth_middleware { httplib::jwt::hs256("secret") });
        },
        [](auto& client) -> net::awaitable<void>
        {
            auto resp = UNWRAP(co_await client.async_get("/protected"));
            REQUIRE(resp.result() == httplib::status::unauthorized);
            co_return;
        });
}

TEST_CASE("JWT: verifier rejects expired token", "[jwt]")
{
    auto now = std::chrono::system_clock::now();
    auto token
        = httplib::jwt::create().set_expires_at(now - 1h).set_subject("alice").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs256("secret")).verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::expired));
}

TEST_CASE("JWT: verifier rejects not-yet-valid token", "[jwt]")
{
    auto now = std::chrono::system_clock::now();
    auto token
        = httplib::jwt::create().set_not_before(now + 1h).set_subject("alice").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs256("secret")).verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::not_yet_valid));
}

TEST_CASE("JWT: verifier respects clock skew for expiration", "[jwt]")
{
    auto now = std::chrono::system_clock::now();
    auto token = httplib::jwt::create()
                     .set_expires_at(now - std::chrono::seconds(10))
                     .set_subject("alice")
                     .sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    boost::system::error_code ec;

    httplib::jwt::verify(httplib::jwt::hs256("secret")).verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::expired));

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_clock_skew(std::chrono::seconds(60)).verify(decoded, ec);
    REQUIRE_FALSE(ec);
}

TEST_CASE("JWT: verifier rejects mismatched algorithm", "[jwt]")
{
    auto token = httplib::jwt::create().set_subject("alice").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    REQUIRE(decoded.get_algorithm() == "HS256");

    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs384("secret")).verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::algorithm_mismatch));
}

TEST_CASE("JWT: valid token passes all time checks", "[jwt]")
{
    auto now = std::chrono::system_clock::now();
    auto token = httplib::jwt::create().set_not_before(now - 1h).set_expires_at(now + 1h).set_subject("alice").sign(
        httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_subject("alice").verify(decoded, ec);
    REQUIRE_FALSE(ec);
}
