#include "common.hpp"
#include "httplib/server/middleware/data.hpp"
#include "httplib/server/middleware/jwt_auth.hpp"
#include "httplib/server/request.hpp"
#include "httplib/server/response.hpp"
#include "httplib/util/jwt.hpp"

#include <catch2/catch_test_macros.hpp>
#include <jwt-cpp/jwt.h>
#include <jwt-cpp/traits/boost-json/traits.h>

using namespace std::chrono_literals;
using traits = jwt::traits::boost_json;
using claim = jwt::basic_claim<traits>;

TEST_CASE("JWT: build and sign with HS256", "[jwt]")
{
    auto token
        = httplib::jwt::create().set_type("access").set_issued_now().set_expires_in(1h).set_subject("user123").sign(
            httplib::jwt::hs256("my-secret"));

    REQUIRE(!token.empty());
    REQUIRE(std::count(token.begin(), token.end(), '.') == 2);
}

TEST_CASE("JWT: minimal token", "[jwt]")
{
    auto token = httplib::jwt::create().sign(httplib::jwt::hs256("x"));
    REQUIRE(!token.empty());
}

TEST_CASE("JWT: decode token", "[jwt]")
{
    auto token = httplib::jwt::create().set_subject("user123").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    REQUIRE(decoded.get_payload_claim<std::string>("sub") == "user123");
}

TEST_CASE("JWT: verify token", "[jwt]")
{
    auto token = httplib::jwt::create().set_payload_claim("id", 42).sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();
    REQUIRE(decoded.verify(httplib::jwt::hs256("secret")));

    boost::system::error_code ec;
    REQUIRE_FALSE(decoded.verify(httplib::jwt::hs256("wrong"), ec));
    REQUIRE(ec == make_error_code(httplib::jwt::error::signature_verification));
}

TEST_CASE("JWT: verifier with claims", "[jwt]")
{
    auto token = httplib::jwt::create().set_issuer("my-app").set_subject("alice").set_id("jti-1").set_issued_now().sign(
        httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs256("secret"))
        .with_issuer("my-app")
        .with_subject("alice")
        .with_id("jti-1")
        .verify(decoded, ec);
    REQUIRE_FALSE(ec);

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_issuer("wrong").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::issuer_mismatch));
}

TEST_CASE("JWT: cross-validate with jwt-cpp", "[jwt]")
{
    auto token = httplib::jwt::create()
                     .set_issuer("httplib")
                     .set_subject("test")
                     .set_id("abc123")
                     .set_issued_now()
                     .set_expires_in(1h)
                     .sign(httplib::jwt::hs256("shared-secret"));

    // jwt-cpp can decode and verify our token
    auto decoded = ::jwt::decode<traits>(token);
    REQUIRE(decoded.has_issuer());
    REQUIRE(decoded.get_issuer() == "httplib");
    REQUIRE(decoded.has_subject());
    REQUIRE(decoded.get_subject() == "test");
    REQUIRE(decoded.get_algorithm() == "HS256");

    auto verifier
        = ::jwt::verify<traits>().allow_algorithm(::jwt::algorithm::hs256 { "shared-secret" }).with_issuer("httplib");
    verifier.verify(decoded);

    // Also verify our decoded token matches jwt-cpp's
    auto our_decoded = httplib::jwt::decode(token).value();
    REQUIRE(our_decoded.get_algorithm() == "HS256");
    REQUIRE(our_decoded.has_issuer());
    REQUIRE(our_decoded.get_issuer() == "httplib");
    REQUIRE(our_decoded.has_subject());
    REQUIRE(our_decoded.get_subject() == "test");
    REQUIRE(our_decoded.has_id());
    REQUIRE(our_decoded.get_id() == "abc123");
}

TEST_CASE("JWT: verify tokens generated by jwt-cpp", "[jwt]")
{
    // jwt-cpp generates a token, our library decodes and verifies it
    auto jwt_cpp_token
        = ::jwt::create<traits>().set_issuer("jwt-cpp").set_subject("cross").set_id("x123").set_issued_now().sign(
            ::jwt::algorithm::hs256 { "shared-secret" });

    auto decoded = httplib::jwt::decode(jwt_cpp_token).value();
    REQUIRE(decoded.get_algorithm() == "HS256");
    REQUIRE(decoded.has_issuer());
    REQUIRE(decoded.get_issuer() == "jwt-cpp");
    REQUIRE(decoded.has_subject());
    REQUIRE(decoded.get_subject() == "cross");
    REQUIRE(decoded.has_id());
    REQUIRE(decoded.get_id() == "x123");

    httplib::jwt::verify(httplib::jwt::hs256("shared-secret"))
        .with_issuer("jwt-cpp")
        .with_subject("cross")
        .with_id("x123")
        .verify(decoded);
}

TEST_CASE("JWT: different secrets produce different tokens", "[jwt]")
{
    auto t1 = httplib::jwt::create().set_issued_now().sign(httplib::jwt::hs256("s1"));
    auto t2 = httplib::jwt::create().set_issued_now().sign(httplib::jwt::hs256("s2"));
    REQUIRE(t1 != t2);
}

TEST_CASE("JWT: HS384 and HS512", "[jwt]")
{
    auto t384 = httplib::jwt::create().set_subject("test").sign(httplib::jwt::hs384("secret"));

    auto decoded384 = httplib::jwt::decode(t384).value();
    REQUIRE(decoded384.get_algorithm() == "HS384");
    REQUIRE(decoded384.verify(httplib::jwt::hs384("secret")));

    auto t512 = httplib::jwt::create().set_subject("test").sign(httplib::jwt::hs512("secret"));

    auto decoded512 = httplib::jwt::decode(t512).value();
    REQUIRE(decoded512.get_algorithm() == "HS512");
    REQUIRE(decoded512.verify(httplib::jwt::hs512("secret")));
}

TEST_CASE("JWT: header claims and time claims", "[jwt]")
{
    auto now = std::chrono::system_clock::now();
    auto token = httplib::jwt::create()
                     .set_type("JWT")
                     .set_content_type("JWT")
                     .set_key_id("key-1")
                     .set_header_claim("custom-hdr", "hdr-val")
                     .set_audience("api.example.com")
                     .set_not_before(now - 1h)
                     .set_expires_at(now + 1h)
                     .set_issued_at(now)
                     .set_payload_claim("role", "admin")
                     .sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    REQUIRE(decoded.get_algorithm() == "HS256");
    REQUIRE(decoded.has_audience());
    REQUIRE(decoded.get_audience() == "api.example.com");
    REQUIRE(decoded.has_not_before());
    REQUIRE(decoded.has_expires_at());
    REQUIRE(decoded.has_issued_at());
}

TEST_CASE("JWT: verifier with_audience and with_claim", "[jwt]")
{
    auto token = httplib::jwt::create()
                     .set_audience("api.example.com")
                     .set_payload_claim("role", "admin")
                     .sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    boost::system::error_code ec;
    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_audience("api.example.com").verify(decoded, ec);
    REQUIRE_FALSE(ec);

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_audience("wrong").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::audience_mismatch));

    httplib::jwt::verify(httplib::jwt::hs256("secret"))
        .with_claim("role", [](boost::json::value const& v) { return v == "admin"; })
        .verify(decoded, ec);
    REQUIRE_FALSE(ec);
}

TEST_CASE("JWT: error_code for each mismatch type", "[jwt]")
{
    auto token = httplib::jwt::create().set_subject("alice").set_id("jti-x").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    boost::system::error_code ec;

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_subject("bob").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::subject_mismatch));

    httplib::jwt::verify(httplib::jwt::hs256("secret")).with_id("wrong-id").verify(decoded, ec);
    REQUIRE(ec == make_error_code(httplib::jwt::error::id_mismatch));
}

TEST_CASE("JWT: decoded_jwt accessors", "[jwt]")
{
    auto token = httplib::jwt::create().set_issuer("test-iss").sign(httplib::jwt::hs256("secret"));

    auto decoded = httplib::jwt::decode(token).value();

    REQUIRE(!decoded.get_token().empty());
    REQUIRE(!decoded.get_signature().empty());
    REQUIRE(decoded.get_header().is_object());
    REQUIRE(decoded.get_payload().is_object());
}

TEST_CASE("JWT: verifier allow_algorithm explicitly", "[jwt]")
{
    auto token = httplib::jwt::create().sign(httplib::jwt::hs256("secret"));
    auto decoded = httplib::jwt::decode(token).value();

    httplib::jwt::verifier v;
    v.allow_algorithm(httplib::jwt::hs256("secret"));
    boost::system::error_code ec;
    v.verify(decoded, ec);
    REQUIRE_FALSE(ec);
}

TEST_CASE("JWT: middleware auth via Bearer token", "[jwt]")
{
    test_common::test_scaffold ts;
    namespace mw = httplib::server::middleware;

    auto ja = mw::jwt_auth_middleware { httplib::jwt::hs256("secret") };
    ja.with_issuer("my-app");
    ts.router().set_http_handler<http::verb::get>(
        "/protected",
        [](httplib::server::request& req, httplib::server::response& resp)
        {
            auto& jwt = mw::fetch<mw::jwt_auth_middleware>(req);
            resp.set_string_content(jwt.get_subject(), "text/plain");
        },
        ja);

    ts.start();

    auto token = httplib::jwt::create().set_issuer("my-app").set_subject("alice").sign(httplib::jwt::hs256("secret"));

    auto hdrs = httplib::http::fields();
    hdrs.set(http::field::authorization, "Bearer " + token);
    auto resp = UNWRAP(ts.client->send_request(http::verb::get, "/protected", hdrs));
    REQUIRE(resp.result() == http::status::ok);
    REQUIRE(test_common::as_string(resp) == "alice");
}

TEST_CASE("JWT: middleware rejects invalid token", "[jwt]")
{
    test_common::test_scaffold ts;
    namespace mw = httplib::server::middleware;

    ts.router().set_http_handler<http::verb::get>(
        "/protected",
        [](httplib::server::request&, httplib::server::response& resp)
        { resp.set_string_content("ok"sv, "text/plain"sv); },
        mw::jwt_auth_middleware { httplib::jwt::hs256("secret") });

    ts.start();

    auto hdrs = httplib::http::fields();
    hdrs.set(http::field::authorization, "Bearer invalid.token.here");
    auto resp = UNWRAP(ts.client->send_request(http::verb::get, "/protected", hdrs));
    REQUIRE(resp.result() == http::status::unauthorized);
}

TEST_CASE("JWT: middleware rejects missing Bearer", "[jwt]")
{
    test_common::test_scaffold ts;
    namespace mw = httplib::server::middleware;

    ts.router().set_http_handler<http::verb::get>(
        "/protected",
        [](httplib::server::request&, httplib::server::response& resp)
        { resp.set_string_content("ok"sv, "text/plain"sv); },
        mw::jwt_auth_middleware { httplib::jwt::hs256("secret") });

    ts.start();

    auto resp = UNWRAP(ts.client->get("/protected"));
    REQUIRE(resp.result() == http::status::unauthorized);
}
